version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: facilityscope_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: facilityscope
      POSTGRES_USER: fs_user
      POSTGRES_PASSWORD: fs_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: facilityscope_app
    depends_on:
      - postgres
    ports:
      - '8080:8080'

volumes:
  pgdata:
